### Registro do usuário
POST https://adonis-ydky.onrender.com/register HTTP/1.1
Content-Type:application/json

{
    "name": "Maria",
    "cpf": "02071148622",
    "password": "12345"
}

### Login do usuário
POST https://adonis-ydky.onrender.com/login HTTP/1.1
Content-Type:application/json

{
    "cpf": "02071148622",
    "password": "12345"
}